name: CI

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install sarif-fmt & clippy-sarif
        uses: taiki-e/install-action@v2
        with:
          tool: sarif-fmt,clippy-sarif
      - name: Run clippy
        run: cargo clippy --message-format=json | clippy-sarif | tee results.sarif | sarif-fmt
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  miri:
    name: Miri [${{ matrix.endianness }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        endianness:
          - littleendian
          - bigendian
        include:
          - endianness: littleendian
            target: x86_64-unknown-linux-gnu
          - endianness: bigendian
            target: s390x-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
          targets: ${{ matrix.target }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run miri
        run: cargo miri nextest run -P ci-miri --target ${{ matrix.target }}
      - name: Report
        uses: dorny/test-reporter@v2
        if: '!cancelled()'
        with:
          name: miri [${{ matrix.endianness }}]
          path: target/nextest/ci-miri/report-miri.xml
          reporter: java-junit
          fail-on-error: true

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run tests
        run: cargo nextest run -P ci
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: '!cancelled()'
        with:
          name: nextest
          path: target/nextest/ci/report.xml
          reporter: java-junit
          fail-on-error: true
