name: Test Coverage

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    name: Collect test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install nextest & llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov
      - name: Collect coverage data
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov --no-report --doc
          cargo llvm-cov report --doctests --cobertura --output-path coverage.xml
      - name: Generate report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          output: both
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Write to job summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      # - name: Upload coverage data to codecov
      #   uses: codecov/codecov-action@v5
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: lcov.info
